version: '1.0.0'

services:
  backend:
    image: dmitriynazarov/diplom-backend:v1
    ports:
      - 5500:5500
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "mysecretpassword"
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"


